### ISSUE TITLE
error while loading terminal

### ISSUE THREAD

**Issue by gauthamzz** [denysdovhan/robbyrussell#10]
```js
async function gitRepoAsync(config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gautham/.nvm/versions/node/v6.9.2/lib/node_modules/robbyrussell/robbyrussell:3:22)
    at Module._compile (module.js:570:32)
/home/gautham/.nvm/versions/node/v6.9.2/lib/node_modules/robbyrussell/index.js:63
async function gitRepoAsync(config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gautham/.nvm/versions/node/v6.9.2/lib/node_modules/robbyrussell/robbyrussell:3:22)
    at Module._compile (module.js:570:32)
/home/gautham/.nvm/versions/node/v6.9.2/lib/node_modules/robbyrussell/index.js:63
async function gitRepoAsync(config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gautham/.nvm/versions/node/v6.9.2/lib/node_modules/robbyrussell/robbyrussell:3:22)
    at Module._compile (module.js:570:32)
```

I got the above error while opening terminal each time after installing

**Comment by denysdovhan** [comment]
Hi, @gauthamzz!

Probably you've missed a warning while installing `robbyrussell`. `robbyrussell` [requires Node.js >= 7.6.0](https://github.com/denysdovhan/robbyrussell/blob/master/package.json#L12-L14) for `async/await`. I believe upgrade would help you.
